# Generated by Django 2.1.2 on 2018-10-03 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled', max_length=180)),
                ('total_budget', models.FloatField(blank=True, null=True)),
                ('remaining_budget', models.FloatField(blank=True, null=True)),
                ('date_uploaded', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='No Description', max_length=180)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('date_uploaded', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('action_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWL', 'Withdrawl')], max_length=16)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='budgets.Budget')),
            ],
        ),
    ]
